(function(root){
const D=root.NewEarthData||(typeof require!=='undefined'?require('./data.js'):null), clone=x=>JSON.parse(JSON.stringify(x));
function seeded(seed=1){let s=(seed>>>0)||1;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}function rand(s){const r=seeded(s.rngState);const v=r();s.rngState=Math.floor(r()*4294967295)||1;return v}
const has=(s,id)=>s.projects.includes(id), expert=(s,id)=>s.experts.includes(id), neHas=(s,id)=>s.newEarth?.tech.includes(id);
function danger(round){return D.BALANCE.danger.find(x=>round>=x.from&&round<=x.to)}
function regions(){let a=[];for(const t of ['industry','resources','research'])for(let i=1;i<=6;i++)a.push({id:`${t}-${i}`,type:t,index:i,status:2,meeples:0,buildings:[],shield:0,underground:false});a.find(x=>x.id==='industry-1').meeples=2;a.find(x=>x.id==='resources-1').meeples=2;a.find(x=>x.id==='research-1').meeples=1;return a}
function newGame(seed=1){return{phase:'earth',round:1,seed,rngState:seed,money:10,material:4,science:2,population:5,inactiveMeeples:0,actions:5,regions:regions(),projects:[],experts:[],technologies:Object.fromEntries(D.TECHNOLOGIES.map(t=>[t.id,'locked'])),rocket:{habitat:0,cargo:0,tech:0,engine:false,discountMoney:0,cargoDiscount:false},event:null,highTechUsed:false,vargaUsed:false,pendingRocketPenalty:false,earthLosses:{regions:0,buildings:0,meeples:0},log:[],newEarth:null,gameOver:false}}
function pay(s,c){for(const k of ['money','material','science'])if((s[k]||0)<(c[k]||0))return false;for(const k of ['money','material','science'])s[k]-=c[k]||0;return true}function costText(c){return Object.entries(c).filter(([,v])=>v).map(([k,v])=>`${v} ${k==='money'?'G':k==='material'?'M':'W'}`).join(' + ')||'kostenlos'}function act(s){if(s.actions<1)return false;s.actions--;return true}
function income(s){let x={money:4,material:0,science:0},remaining=Math.max(0,s.population-s.inactiveMeeples);for(const r of s.regions){const m=Math.min(r.meeples,remaining);remaining-=m;if(!m||!r.status)continue;const p=D.REGION_TYPES[r.type][r.status===2?'intact':'damaged'];for(const[k,v]of Object.entries(p))x[k]=(x[k]||0)+v*m}for(const r of s.regions)if(r.status)for(const id of r.buildings){for(const[k,v]of Object.entries(D.STANDARD_BUILDINGS[id]?.production||{}))x[k]=(x[k]||0)+v}const mines=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='mine').length,0),fac=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='factory').length,0),labs=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='researchCenter').length,0);if(has(s,'deepDrilling')&&mines)x.material+=2;if(has(s,'autoChain')&&mines)x.material+=3;if(has(s,'industry40')&&fac)x.money+=4;if(has(s,'globalContracts')&&s.event?.id!=='supply')x.money+=3;if(has(s,'aiResearch')&&labs)x.science+=2;if(has(s,'openScience'))x.science++;if(has(s,'recycling'))x.material++;if(has(s,'mobileResearch'))x.science++;if(has(s,'robotFarm'))x.money+=2;if(has(s,'autonomousMining'))x.material+=2;if(s.event?.id==='brainDrain')x.science=Math.max(0,x.science-1);let lm=0,lg=0;if(s.event?.id==='drought')lm=Math.min(6,s.regions.filter(r=>r.type==='resources'&&r.status).length);if(s.event?.id==='heat')lg=fac;if(s.event?.id==='energy')lg=2*fac;if(has(s,'redundantGrid')){if(lg>=lm)lg=Math.max(0,lg-2);else lm=Math.max(0,lm-2)}x.money=Math.max(0,x.money-lg);x.material=Math.max(0,x.material-lm);return x}
function eventFor(s,forced){if(forced){const e=D.EVENTS.find(x=>x.id===forced);if(e)return e}const p=D.EVENTS.filter(e=>e.tier===danger(s.round).name);return p[Math.floor(rand(s)*p.length)]}
function peekEvent(s){const c=clone(s);return eventFor(c)}
function target(s,e,used=[]){let c=s.regions.filter(r=>r.status&&!used.includes(r.id));if(!c.length)c=s.regions.filter(r=>r.status);if(e.prioritizeDamaged&&c.some(r=>r.status===1))c=c.filter(r=>r.status===1);else if(e.prefer&&c.some(r=>e.prefer.includes(r.type)))c=c.filter(r=>e.prefer.includes(r.type));return c[Math.floor(rand(s)*c.length)]}
function damage(s,r){if(!r||!r.status)return;if(r.shield){r.shield--;return}r.status--;if(!r.status){s.earthLosses.regions++;s.earthLosses.buildings+=r.buildings.length;r.buildings=[];if(r.meeples){const n=r.meeples;r.meeples=0;const safe=s.regions.find(x=>x.status&&x.type===r.type)||s.regions.find(x=>x.status);if(safe)safe.meeples+=n;if(s.round<=3){}else if(s.round<=6){if(!has(s,'evacNet'))s.inactiveMeeples+=n}else s._danger=(s._danger||0)+n}}}
function drawEvent(s,forced){if(s.phase!=='earth'||s.event)return null;let e=eventFor(s,forced);if(s.skipNextEvent&&!forced){s.skipNextEvent=false;e=eventFor(s)}s.event=e;let used=[];for(let i=0;i<e.damage;i++){const r=target(s,e,e.different?used:[]);if(r){damage(s,r);used.push(r.id)}}if(e.extraDamaged){const c=s.regions.filter(r=>r.status===1);if(c.length)damage(s,c[Math.floor(rand(s)*c.length)])}if(e.id==='flight'){const c=s.regions.filter(r=>r.status===1&&r.meeples);if(c.length&&!has(s,'evacNet'))s.inactiveMeeples++}if(e.id==='collapse'&&s._danger){const c=(has(s,'evacNet')?1:3)*s._danger;if(s.money>=c)s.money-=c;else{s.population=Math.max(1,s.population-s._danger);s.earthLosses.meeples+=s._danger}s._danger=0}if(e.id==='lastWindow')s.pendingRocketPenalty=true;return e}
function moveMeeple(s,fromId,toId){const a=s.regions.find(r=>r.id===fromId),b=s.regions.find(r=>r.id===toId);if(s.phase!=='earth'||!a||!b||a===b||a.meeples<1||!b.status)return{ok:false,msg:'Meeple kann dort nicht eingesetzt werden.'};a.meeples--;b.meeples++;return{ok:true,msg:`Meeple nach ${D.REGION_TYPES[b.type].name} ${b.index} versetzt.`}}
function vargaSkip(s){if(!expert(s,'varga')||s.vargaUsed)return false;s.vargaUsed=true;s.skipNextEvent=true;return true}
function buildEarth(s,id,rid){const b=D.STANDARD_BUILDINGS[id],r=s.regions.find(x=>x.id===rid);if(!b||!r||!r.status||(b.region!=='any'&&r.type!==b.region))return{ok:false,msg:'Unpassende Region.'};if(id!=='disasterProtection'&&r.buildings.length)return{ok:false,msg:'Region hat bereits ein Gebäude.'};let c=clone(b.cost);if(s.event?.id==='supply'&&!s._built)c.money=(c.money||0)+2;if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,c)){s.actions++;return{ok:false,msg:`Benötigt ${costText(c)}.`}}if(id==='disasterProtection')r.shield++;else r.buildings.push(id);s._built=true;return{ok:true}}
function buyProject(s,id){const p=D.PROJECTS.find(x=>x.id===id);if(!p||has(s,id))return{ok:false,msg:'Nicht verfügbar.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,p.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(p.cost)}.`}}s.projects.push(id);if(id==='openScience')s.science+=3;if(id==='resourceDepot'){s.material+=5;s.rocket.cargoDiscount=true}if(id==='privateSpace')s.rocket.discountMoney=4;if(id==='underground'){const r=s.regions.find(x=>x.buildings.length);if(r)r.underground=true}return{ok:true}}
function hireExpert(s,id){const e=D.EXPERTS.find(x=>x.id===id);if(!e||expert(s,id))return{ok:false,msg:'Nicht verfügbar.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,e.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(e.cost)}.`}}s.experts.push(id);return{ok:true}}
function researchTech(s,id){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(!t||s.technologies[id]!=='locked')return{ok:false,msg:'Nicht verfügbar.'};let c=t.research-(expert(s,'mei')&&['builders','drones','longRover','fabrication'].includes(id)?1:0);if(!s.highTechUsed&&s.regions.some(r=>r.buildings.includes('highTechLab'))){c--;s.highTechUsed=true}c=Math.max(0,c);if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(s.science<c){s.actions++;return{ok:false,msg:`Benötigt ${c} W.`}}s.science-=c;s.technologies[id]='researched';return{ok:true}}
function buildTech(s,id){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(!t||s.technologies[id]!=='researched')return{ok:false,msg:'Erst erforschen.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,t.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(t.cost)}.`}}s.technologies[id]='built';return{ok:true}}
function rocketCost(s,type){let c=clone(D.ROCKET[type].cost);if(has(s,'recycling')&&c.material)c.material=Math.max(1,c.material-1);if(s.rocket.discountMoney)c.money=Math.max(0,(c.money||0)-s.rocket.discountMoney);if(type==='cargo'&&s.rocket.cargoDiscount)c.money=Math.max(0,(c.money||0)-2);if(expert(s,'sato')&&!s._sato)c.material=Math.max(0,(c.material||0)-2);if(expert(s,'petrov')&&!s._petrov&&['habitat','cargo','tech'].includes(type))c.money=Math.max(0,(c.money||0)-3);if(s.pendingRocketPenalty)c.money=(c.money||0)+3;return c}
function buildRocket(s,type){if(!D.ROCKET[type]||type==='base')return{ok:false,msg:'Unbekannt.'};if(type==='engine'&&!D.BALANCE.featureFlags.improvedEngine)return{ok:false,msg:'Verbesserter Antrieb deaktiviert.'};const addons=s.rocket.habitat+s.rocket.cargo+s.rocket.tech;if(D.BALANCE.featureFlags.improvedEngine&&addons>=4&&!s.rocket.engine&&type!=='engine')return{ok:false,msg:'Verbesserter Antrieb nötig.'};const c=rocketCost(s,type);if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,c)){s.actions++;return{ok:false,msg:`Benötigt ${costText(c)}.`}}if(type==='engine')s.rocket.engine=true;else s.rocket[type]++;if(s.rocket.discountMoney)s.rocket.discountMoney=0;if(type==='cargo')s.rocket.cargoDiscount=false;if(expert(s,'sato')&&!s._sato)s._sato=true;if(expert(s,'petrov')&&!s._petrov&&['habitat','cargo','tech'].includes(type))s._petrov=true;return{ok:true}}
function capacities(s){return{people:2+3*s.rocket.habitat,resources:3+(8+(expert(s,'williams')?3:0))*s.rocket.cargo,tech:1+2*s.rocket.tech}}
function transportableTechs(s){return D.TECHNOLOGIES.filter(t=>s.technologies[t.id]==='built').map(t=>t.id).concat(D.PROJECTS.filter(p=>p.transportable&&has(s,p.id)).map(p=>p.id))}
function launch(s,l){const c=capacities(s),people=(l.population||0)+(l.experts||[]).length;if(people>c.people||(l.material||0)>c.resources||(l.tech||[]).length>c.tech)return{ok:false,msg:'Kapazität überschritten.'};if((l.population||0)<1)return{ok:false,msg:'Mindestens 1 Siedler muss mit.'};if(l.material>s.material)return{ok:false,msg:'Zu viel Material.'};for(const id of l.experts||[])if(!expert(s,id))return{ok:false,msg:'Experte nicht vorhanden.'};const allowed=transportableTechs(s);for(const id of l.tech||[])if(!allowed.includes(id))return{ok:false,msg:'Tech nicht transportierbar.'};s.phase='newEarth';s.newEarth={vp:0,material:l.material,landingMaterial:l.material,science:0,food:0,population:l.population,experts:[...(l.experts||[])],tech:[...(l.tech||[])],settlements:1,buildings:{mine:0,farm:0,lab:0,rover:0},radius:2,known:[],analyzed:[],actions:l.population,rounds:0,first:{farm:true,mine:true,building:true,secondBuilding:true,settlement:true,exobio:true},prodHistory:[]};if(neHas(s,'oxygen'))s.newEarth.radius++;s.newEarth.flexProd=neHas(s,'fusion')?2:0;if(neHas(s,'mobileResearch'))s.newEarth.science+=2;return{ok:true}}
function neCost(s,type){const n=s.newEarth;let c=D.NEW_EARTH.buildings[type].cost;if(neHas(s,'fabrication')&&!['settlement','rover'].includes(type))c--;if(expert(s,'sato')&&n.first.building)c-=2;if(neHas(s,'builders')&&n.first.building&&type!=='settlement')c=0;else if(neHas(s,'builders')&&n.first.secondBuilding&&type!=='settlement')c-=2;if(type==='farm'&&n.first.farm){if(neHas(s,'extremophile'))c=0;if(neHas(s,'robotFarm'))c-=2}if(type==='mine'&&n.first.mine){if(neHas(s,'autonomousMining'))c-=3;if(expert(s,'johnson'))c-=2}if(type==='settlement'&&n.first.settlement&&neHas(s,'habitats'))c-=3;return Math.max(0,c)}
function neFoodProd(s){const n=s.newEarth;return 1+2*n.buildings.farm+(expert(s,'alvarez')?n.buildings.farm:0)+(n.bonusFoodProd||0)+(neHas(s,'foodRecycler')?2:0)}
function neBuild(s,type){const n=s.newEarth;if(n.actions<1)return{ok:false,msg:'Keine Aktion.'};const c=neCost(s,type);if(n.material<c)return{ok:false,msg:`Benötigt ${c} M.`};const supplyNeed=neHas(s,'foodRecycler')?0:n.settlements+1;if(type==='settlement'&&neFoodProd(s)<supplyNeed)return{ok:false,msg:'Versorgung fehlt.'};n.actions--;n.material-=c;if(type==='settlement'){n.settlements++;n.vp++;n.radius++;n.first.settlement=false}else n.buildings[type]++;if(type==='farm')n.first.farm=false;if(type==='mine')n.first.mine=false;if(type!=='settlement'){if(n.first.building)n.first.building=false;else n.first.secondBuilding=false}return{ok:true}}
function explorationOptions(s,forced){const n=s.newEarth;let count=3+(neHas(s,'drones')?1:0)+(expert(s,'johnson')?1:0)+(expert(s,'okafor')?1:0);let pool=D.DISCOVERIES.filter(d=>!n.known.some(k=>k.id===d.id)&&!n.analyzed.includes(d.id));if(forced){const d=D.DISCOVERIES.find(x=>x.id===forced);if(d&&!pool.some(x=>x.id===d.id))pool.unshift(d)}let out=[];while(pool.length&&out.length<count){const i=Math.floor(rand(s)*pool.length);out.push(pool.splice(i,1)[0])}return out}
function explore(s,id,forced){const n=s.newEarth;if(n.actions<1)return{ok:false,msg:'Keine Aktion.'};if(n.buildings.rover<1)return{ok:false,msg:'Baue zuerst einen Rover.'};const o=explorationOptions(s,forced),d=o.find(x=>x.id===id)||o[0];if(!d)return{ok:false,msg:'Nichts mehr zu entdecken.'};n.actions--;n.known.push(clone(d));return{ok:true,options:o,choice:d}}
function analyze(s,id){const n=s.newEarth,d=n.known.find(x=>x.id===id);if(!d)return{ok:false,msg:'Fund nicht bekannt.'};let c=d.analysis;if(['alien','biology'].includes(d.type)&&neHas(s,'exobioLab'))c-=2;if(['alien','biology'].includes(d.type)&&expert(s,'okafor'))c--;c=Math.max(0,c);if(n.actions<1||n.science<c)return{ok:false,msg:`Benötigt Aktion und ${c} W.`};n.actions--;n.science-=c;n.vp+=d.vp||1;if(neHas(s,'exobioLab')&&n.first.exobio){n.vp++;n.first.exobio=false}n.material+=d.material||0;n.science+=d.science||0;n.bonusMaterialProd=(n.bonusMaterialProd||0)+(d.materialProd||0);n.bonusFoodProd=(n.bonusFoodProd||0)+(d.foodProd||0);n.bonusScienceProd=(n.bonusScienceProd||0)+(d.scienceProd||0);n.known=n.known.filter(x=>x.id!==id);n.analyzed.push(id);return{ok:true}}
function neProduction(s){const n=s.newEarth,p={material:1+2*n.buildings.mine+(n.bonusMaterialProd||0)+(n.flexProd||0),food:neFoodProd(s),science:2*n.buildings.lab+(n.bonusScienceProd||0)};n.material+=p.material;n.food+=p.food;n.science+=p.science;return p}
function endRound(s){if(s.phase==='earth'){if(!s.event)drawEvent(s);const i=income(s);s.money+=i.money;s.material+=i.material;s.science+=i.science;s.inactiveMeeples=0;s.round++;s.actions=s.population;s.event=null;s.highTechUsed=false;s._built=false;s.pendingRocketPenalty=false;return i}const p=neProduction(s);s.newEarth.rounds++;s.newEarth.prodHistory.push(clone(p));if(s.newEarth.vp>=D.BALANCE.winVP)s.gameOver=true;s.round++;s.newEarth.actions=s.newEarth.population;return p}
const api={newGame,danger,income,peekEvent,drawEvent,moveMeeple,vargaSkip,buildEarth,buyProject,hireExpert,researchTech,buildTech,rocketCost,buildRocket,capacities,transportableTechs,launch,neCost,neBuild,neFoodProd,explorationOptions,explore,analyze,neProduction,endRound,costText,exportState:JSON.stringify,importState:JSON.parse,has,expert};root.NewEarthEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
