(function(root){
const D=root.NewEarthData||(typeof require!=='undefined'?require('./data.js'):null), clone=x=>JSON.parse(JSON.stringify(x));
function seeded(seed=1){let s=(seed>>>0)||1;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}function rand(s){const r=seeded(s.rngState);const v=r();s.rngState=Math.floor(r()*4294967295)||1;return v}
const has=(s,id)=>s.projects.includes(id), expert=(s,id)=>s.experts.includes(id), neHas=(s,id)=>s.newEarth?.tech.includes(id);
function danger(round){return D.BALANCE.danger.find(x=>round>=x.from&&round<=x.to)}
function regions(){let a=[];for(const t of ['industry','resources','research'])for(let i=1;i<=6;i++)a.push({id:`${t}-${i}`,type:t,index:i,status:2,meeples:0,buildings:[],shield:0,underground:false});a.find(x=>x.id==='industry-1').meeples=2;a.find(x=>x.id==='resources-1').meeples=2;a.find(x=>x.id==='research-1').meeples=1;return a}
function shuffleWithState(s,arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rand(s)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function initMarkets(s){s.projectDeck=shuffleWithState(s,D.PROJECTS.map(x=>x.id));s.projectMarket=[];refillProjectMarket(s);s.expertDeck=shuffleWithState(s,D.EXPERTS.map(x=>x.id));s.expertMarket=[];refillExpertMarket(s)}
function refillProjectMarket(s){s.projectMarket=s.projectMarket||[];s.projectDeck=s.projectDeck||[];while(s.projectMarket.length<5&&s.projectDeck.length)s.projectMarket.push(s.projectDeck.shift())}
function refillExpertMarket(s){s.expertMarket=s.expertMarket||[];s.expertDeck=s.expertDeck||[];while(s.expertMarket.length<4&&s.expertDeck.length)s.expertMarket.push(s.expertDeck.shift())}
function refreshProjectMarket(s){if(s.actions<1)return{ok:false,msg:'Keine Aktion.'};if(!s.projectDeck?.length)return{ok:false,msg:'Projektstapel leer.'};s.actions--;s.projectDeck.push(...s.projectMarket);s.projectMarket=[];s.projectDeck=shuffleWithState(s,s.projectDeck);refillProjectMarket(s);return{ok:true,msg:'Projektmarkt erneuert.'}}
function newGame(seed=1){const st=(root.NE_DATA&&root.NE_DATA.C&&root.NE_DATA.C.start)||{money:10,material:4,science:2,population:5};const s={phase:'earth',round:1,seed,rngState:seed,money:st.money,material:st.material,science:st.science,population:st.population,inactiveMeeples:0,actions:5,regions:regions(),projects:[],experts:[],technologies:Object.fromEntries(D.TECHNOLOGIES.map(t=>[t.id,'locked'])),rocket:{habitat:0,cargo:0,tech:0,engine:false,prefabFarm:0,prefabMine:0,prefabLab:0,roverHangar:0,discountMoney:0,cargoDiscount:false},event:null,forecast:[],highTechUsed:false,vargaUsed:false,pendingRocketPenalty:false,earthLosses:{regions:0,buildings:0,meeples:0},log:[],newEarth:null,gameOver:false};initMarkets(s);makeForecast(s);return s}
function pay(s,c){for(const k of ['money','material','science'])if((s[k]||0)<(c[k]||0))return false;for(const k of ['money','material','science'])s[k]-=c[k]||0;return true}function costText(c){return Object.entries(c).filter(([,v])=>v).map(([k,v])=>`${v} ${k==='money'?'G':k==='material'?'M':'W'}`).join(' + ')||'kostenlos'}function act(s){if(s.actions<1)return false;s.actions--;return true}
function income(s){let x={money:4,material:0,science:0},remaining=Math.max(0,s.population-s.inactiveMeeples);for(const r of s.regions){const m=Math.min(r.meeples,remaining);remaining-=m;if(!m||!r.status)continue;const p=D.REGION_TYPES[r.type][r.status===2?'intact':'damaged'];for(const[k,v]of Object.entries(p))x[k]=(x[k]||0)+v*m}for(const r of s.regions)if(r.status)for(const id of r.buildings){for(const[k,v]of Object.entries(D.STANDARD_BUILDINGS[id]?.production||{}))x[k]=(x[k]||0)+v}const mines=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='mine').length,0),fac=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='factory').length,0),labs=s.regions.reduce((n,r)=>n+r.buildings.filter(x=>x==='researchCenter').length,0);if(has(s,'deepDrilling')&&mines)x.material+=2;if(has(s,'automatedChain')&&mines)x.material+=3;if(has(s,'industry40')&&fac)x.money+=4;if(has(s,'globalContracts')&&s.event?.id!=='supply')x.money+=3;if(has(s,'aiResearch')&&labs)x.science+=2;if(has(s,'openScience'))x.science++;if(has(s,'recycling'))x.material++;if(has(s,'mobileResearch'))x.science++;if(has(s,'robotFarm'))x.money+=2;if(has(s,'autonomousMining'))x.material+=2;if(s.event?.id==='brainDrain')x.science=Math.max(0,x.science-1);let lm=0,lg=0;if(s.event?.id==='drought')lm=Math.min(6,s.regions.filter(r=>r.type==='resources'&&r.status).length);if(s.event?.id==='heat')lg=fac;if(s.event?.id==='energy')lg=2*fac;if(has(s,'redundantGrid')){if(lg>=lm)lg=Math.max(0,lg-2);else lm=Math.max(0,lm-2)}x.money=Math.max(0,x.money-lg);x.material=Math.max(0,x.material-lm);return x}
function makeForecast(s){const dg=danger(s.round),count=dg.name==='Instabilität'?2:dg.name==='Krise'?3:4,pool=s.regions.filter(r=>r.status),out=[];while(pool.length&&out.length<count){const i=Math.floor(rand(s)*pool.length);out.push(pool.splice(i,1)[0].id)}s.forecast=out;return out}
function forecastRegions(s){return (s.forecast||[]).map(id=>s.regions.find(r=>r.id===id)).filter(Boolean)}
function eventFor(s,forced){if(forced){const e=D.EVENTS.find(x=>x.id===forced);if(e)return e}const p=D.EVENTS.filter(e=>e.tier===danger(s.round).name);return p[Math.floor(rand(s)*p.length)]}
function peekEvent(s){const c=clone(s);return eventFor(c)}
function target(s,e,used=[]){let c=s.regions.filter(r=>r.status&&!used.includes(r.id));const warned=c.filter(r=>(s.forecast||[]).includes(r.id));if(warned.length)c=warned;if(!c.length)c=s.regions.filter(r=>r.status);if(e.prioritizeDamaged&&c.some(r=>r.status===1))c=c.filter(r=>r.status===1);else if(e.prefer&&c.some(r=>e.prefer.includes(r.type)))c=c.filter(r=>e.prefer.includes(r.type));return c[Math.floor(rand(s)*c.length)]}
function damage(s,r){if(!r||!r.status)return;if(r.shield){r.shield--;return}r.status--;if(!r.status){s.earthLosses.regions++;s.earthLosses.buildings+=r.buildings.length;r.buildings=[];if(r.meeples){const n=r.meeples;r.meeples=0;const safe=s.regions.find(x=>x.status&&x.type===r.type)||s.regions.find(x=>x.status);if(safe)safe.meeples+=n;if(s.round<=3){}else if(s.round<=6){if(!has(s,'evacNetwork'))s.inactiveMeeples+=n}else s._danger=(s._danger||0)+n}}}
function drawEvent(s,forced){if(s.phase!=='earth'||s.event)return null;let e=eventFor(s,forced);if(s.skipNextEvent&&!forced){s.skipNextEvent=false;e=eventFor(s)}s.event=e;let used=[];for(let i=0;i<e.damage;i++){const r=target(s,e,e.different?used:[]);if(r){damage(s,r);used.push(r.id)}}if(e.extraDamaged){const c=s.regions.filter(r=>r.status===1);if(c.length)damage(s,c[Math.floor(rand(s)*c.length)])}if(e.id==='flight'){const c=s.regions.filter(r=>r.status===1&&r.meeples);if(c.length&&!has(s,'evacNetwork'))s.inactiveMeeples++}if(e.id==='collapse'&&s._danger){const c=(has(s,'evacNetwork')?1:3)*s._danger;if(s.money>=c)s.money-=c;else{s.population=Math.max(1,s.population-s._danger);s.earthLosses.meeples+=s._danger}s._danger=0}if(e.id==='lastWindow')s.pendingRocketPenalty=true;return e}
function moveMeeple(s,fromId,toId){const a=s.regions.find(r=>r.id===fromId),b=s.regions.find(r=>r.id===toId);if(s.phase!=='earth'||!a||!b||a===b||a.meeples<1||!b.status)return{ok:false,msg:'Meeple kann dort nicht eingesetzt werden.'};a.meeples--;b.meeples++;return{ok:true,msg:`Meeple nach ${D.REGION_TYPES[b.type].name} ${b.index} versetzt.`}}
function vargaSkip(s){if(!expert(s,'varga')||s.vargaUsed)return false;s.vargaUsed=true;s.skipNextEvent=true;return true}
function buildEarth(s,id,rid){const b=D.STANDARD_BUILDINGS[id],r=s.regions.find(x=>x.id===rid);if(!b||!r||!r.status||(b.region!=='any'&&r.type!==b.region))return{ok:false,msg:'Unpassende Region.'};if(id!=='disasterProtection'&&r.buildings.length)return{ok:false,msg:'Region hat bereits ein Gebäude.'};let c=clone(b.cost);if(s.event?.id==='supply'&&!s._built)c.money=(c.money||0)+2;if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,c)){s.actions++;return{ok:false,msg:`Benötigt ${costText(c)}.`}}if(id==='disasterProtection')r.shield++;else r.buildings.push(id);s._built=true;return{ok:true}}
function buyProject(s,id){const p=D.PROJECTS.find(x=>x.id===id);if(!p||has(s,id)||!s.projectMarket?.includes(id))return{ok:false,msg:'Dieses Projekt liegt nicht aus.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,p.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(p.cost)}.`}}s.projects.push(id);if(id==='openScience')s.science+=3;if(id==='resourceDepot'){s.material+=5;s.rocket.cargoDiscount=true}if(id==='privateSpace')s.rocket.discountMoney=4;if(id==='underground'){const r=s.regions.find(x=>x.buildings.length);if(r)r.underground=true}s.projectMarket=s.projectMarket.filter(x=>x!==id);refillProjectMarket(s);return{ok:true}}
function hireExpert(s,id){const e=D.EXPERTS.find(x=>x.id===id);if(!e||expert(s,id)||!s.expertMarket?.includes(id))return{ok:false,msg:'Dieser Experte ist nicht verfügbar.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,e.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(e.cost)}.`}}s.experts.push(id);s.expertMarket=s.expertMarket.filter(x=>x!==id);refillExpertMarket(s);return{ok:true}}
function researchTech(s,id){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(!t||s.technologies[id]!=='locked')return{ok:false,msg:'Nicht verfügbar.'};let c=t.research-(expert(s,'mei')&&['builders','drones','longRover','fabrication'].includes(id)?1:0);if(!s.highTechUsed&&s.regions.some(r=>r.buildings.includes('highTechLab'))){c--;s.highTechUsed=true}c=Math.max(0,c);if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(s.science<c){s.actions++;return{ok:false,msg:`Benötigt ${c} W.`}}s.science-=c;s.technologies[id]='researched';return{ok:true}}
function buildTech(s,id){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(!t||s.technologies[id]!=='researched')return{ok:false,msg:'Erst erforschen.'};if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,t.cost)){s.actions++;return{ok:false,msg:`Benötigt ${costText(t.cost)}.`}}s.technologies[id]='built';return{ok:true}}
function rocketCost(s,type){let c=clone(D.ROCKET[type].cost);if(has(s,'recycling')&&c.material)c.material=Math.max(1,c.material-1);if(s.rocket.discountMoney)c.money=Math.max(0,(c.money||0)-s.rocket.discountMoney);if(type==='cargo'&&s.rocket.cargoDiscount)c.money=Math.max(0,(c.money||0)-2);if(expert(s,'sato')&&!s._sato)c.material=Math.max(0,(c.material||0)-2);if(expert(s,'petrov')&&!s._petrov&&['habitat','cargo','tech','prefabFarm','prefabMine','prefabLab','roverHangar'].includes(type))c.money=Math.max(0,(c.money||0)-3);if(s.pendingRocketPenalty)c.money=(c.money||0)+3;return c}
function buildRocket(s,type){if(!D.ROCKET[type]||type==='base')return{ok:false,msg:'Unbekannt.'};if(['prefabFarm','prefabMine','roverHangar'].includes(type)&&capacities(s).resources<1)return{ok:false,msg:'Kein freier Frachtplatz für dieses Modul.'};if(type==='prefabLab'&&capacities(s).tech<1)return{ok:false,msg:'Kein freier Techplatz für dieses Modul.'};if(type==='engine'&&!D.BALANCE.featureFlags.improvedEngine)return{ok:false,msg:'Verbesserter Antrieb deaktiviert.'};const addons=s.rocket.habitat+s.rocket.cargo+s.rocket.tech+s.rocket.prefabFarm+s.rocket.prefabMine+s.rocket.prefabLab+s.rocket.roverHangar;if(D.BALANCE.featureFlags.improvedEngine&&addons>=4&&!s.rocket.engine&&type!=='engine')return{ok:false,msg:'Verbesserter Antrieb nötig.'};const c=rocketCost(s,type);if(!act(s))return{ok:false,msg:'Keine Aktion.'};if(!pay(s,c)){s.actions++;return{ok:false,msg:`Benötigt ${costText(c)}.`}}if(type==='engine')s.rocket.engine=true;else s.rocket[type]=(s.rocket[type]||0)+1;if(s.rocket.discountMoney)s.rocket.discountMoney=0;if(type==='cargo')s.rocket.cargoDiscount=false;if(expert(s,'sato')&&!s._sato)s._sato=true;if(expert(s,'petrov')&&!s._petrov&&['habitat','cargo','tech','prefabFarm','prefabMine','prefabLab','roverHangar'].includes(type))s._petrov=true;return{ok:true}}
function capacities(s){const cargoRaw=3+(8+(expert(s,'williams')?3:0))*s.rocket.cargo,techRaw=1+2*s.rocket.tech,cargoUsed=(s.rocket.prefabFarm||0)+(s.rocket.prefabMine||0)+(s.rocket.roverHangar||0),techUsed=(s.rocket.prefabLab||0);return{people:2+3*s.rocket.habitat,resources:Math.max(0,cargoRaw-cargoUsed),tech:Math.max(0,techRaw-techUsed),cargoRaw,techRaw,cargoUsed,techUsed}}
function transportableTechs(s){return D.TECHNOLOGIES.filter(t=>s.technologies[t.id]==='built').map(t=>t.id).concat(D.PROJECTS.filter(p=>p.transportable&&has(s,p.id)).map(p=>p.id))}
function launch(s,l){const c=capacities(s),people=(l.population||0)+(l.experts||[]).length;if(people>c.people||(l.material||0)>c.resources||(l.tech||[]).length>c.tech)return{ok:false,msg:'Kapazität überschritten.'};if((l.population||0)<1)return{ok:false,msg:'Mindestens 1 Siedler muss mit.'};if(l.material>s.material)return{ok:false,msg:'Zu viel Material.'};for(const id of l.experts||[])if(!expert(s,id))return{ok:false,msg:'Experte nicht vorhanden.'};const allowed=transportableTechs(s);for(const id of l.tech||[])if(!allowed.includes(id))return{ok:false,msg:'Tech nicht transportierbar.'};s.phase='newEarth';const tiles=makeNETiles(),centers=[[0,0,'Juno Station'],[1,0,'Aurora-Außenposten'],[-1,1,'Kepler-Außenposten']];const landedPeople=l.population+(l.experts||[]).length;let count=(landedPeople>=6&&s.rocket.habitat>=2)?3:(landedPeople>=4&&s.rocket.habitat>=1)?2:1;const per=Math.floor(l.population/count),rest=l.population%count;for(let i=0;i<count;i++){const [q,r,name]=centers[i],t=tiles.find(x=>x.q===q&&x.r===r);t.state='settled';t.discovery={id:'plain',name,type:'generic',terrain:'plain',analysis:0,vp:0,reward:'Landegebiet'};t.settlement=true;t.colonists=per+(i<rest?1:0)}const sites=tiles.filter(t=>t.settlement);for(const t of tiles)if(t.state==='unknown'&&sites.some(a=>hexDist(a,t)<=1)){const pool=D.DISCOVERIES.filter(x=>x.id!=='signal');t.state='surveyed';t.discovery=clone(pool[Math.floor(rand(s)*pool.length)]||pool[0])}const expertActions=Math.min(2,(l.experts||[]).length);s.newEarth={vp:0,material:l.material,landingMaterial:l.material,science:3,food:Math.max(2,l.population),population:l.population,experts:[...(l.experts||[])],tech:[...(l.tech||[])],settlements:count,buildings:{mine:0,farm:0,lab:0,rover:1},radius:2,tiles,selectedTile:sites[0].id,known:tiles.filter(t=>t.state==='surveyed').map(t=>clone(t.discovery)),analyzed:[],developed:[],roverExplored:0,exploreMilestones:0,relics:0,alienMilestones:0,industryMilestones:0,settlementMilestones:0,actions:Math.min(9,l.population+count+expertActions),rounds:0,first:{farm:true,mine:true,building:true,secondBuilding:true,settlement:true,exobio:true},prodHistory:[],redeploy:true,alienResearch:[],contactUnlocked:false,contactLevel:0,contactProd:0,prefabProd:{material:0,food:0,science:0},launchSummary:{settlements:count,population:l.population,revealed:tiles.filter(t=>t.state==='surveyed').length,material:l.material,tech:(l.tech||[]).length,experts:(l.experts||[]).length,range:2+(l.tech||[]).includes('oxygen')+((l.tech||[]).includes('longRover')?2:0)+((l.experts||[]).includes('mei')?1:0)}};if(neHas(s,'oxygen'))s.newEarth.radius++;s.newEarth.flexProd=neHas(s,'fusion')?3:0;if(neHas(s,'mobileResearch'))s.newEarth.science+=2;if(neHas(s,'foodRecycler'))s.newEarth.food+=2;
const prefabSites=s.newEarth.tiles.filter(t=>t.settlement);
const placePrefab=(kind,count)=>{for(let i=0;i<count;i++){const site=prefabSites[i%prefabSites.length];site.buildings.push(kind);s.newEarth.buildings[kind]++;if(kind==='mine')s.newEarth.first.mine=false;if(kind==='farm')s.newEarth.first.farm=false;if(['mine','farm','lab'].includes(kind))s.newEarth.first.building=false}};
placePrefab('farm',s.rocket.prefabFarm||0);placePrefab('mine',s.rocket.prefabMine||0);placePrefab('lab',s.rocket.prefabLab||0);s.newEarth.prefabProd={food:s.rocket.prefabFarm||0,material:s.rocket.prefabMine||0,science:s.rocket.prefabLab||0};
if(neHas(s,'builders')&&s.newEarth.buildings.mine===0){const site=prefabSites[0];if(site){site.buildings.push('mine');s.newEarth.buildings.mine=1;s.newEarth.first.mine=false}}
if(s.rocket.roverHangar){s.newEarth.buildings.rover+=s.rocket.roverHangar;s.newEarth.radius+=s.rocket.roverHangar}
s.newEarth.launchSummary.prefabs={farm:s.rocket.prefabFarm||0,mine:s.rocket.prefabMine||0,lab:s.rocket.prefabLab||0,rover:s.rocket.roverHangar||0};
initMissions(s);return{ok:true,launchSummary:s.newEarth.launchSummary}}
function makeNETiles(){const out=[];let id=0;for(let q=-3;q<=3;q++)for(let r=-3;r<=3;r++){const z=-q-r;if(Math.max(Math.abs(q),Math.abs(r),Math.abs(z))<=3)out.push({id:`hex-${id++}`,q,r,state:'unknown',discovery:null,analyzed:false,settlement:false,buildings:[]})}return out}
function hexDist(a,b){const aq=a.q,ar=a.r,az=-aq-ar,bq=b.q,br=b.r,bz=-bq-br;return Math.max(Math.abs(aq-bq),Math.abs(ar-br),Math.abs(az-bz))}
function neTile(s,id){return s.newEarth.tiles.find(t=>t.id===id)}
function neSettlements(s){return s.newEarth.tiles.filter(t=>t.settlement)}
function neReach(s,t){const range=s.newEarth.radius+(s.newEarth.buildings.rover?1:0)+(neHas(s,'longRover')?2:0)+(hasAlien(s,'alienCartography')?1:0)+(expert(s,'mei')?1:0);return neSettlements(s).some(a=>hexDist(a,t)<=range)}
function frontierTiles(s){return s.newEarth.tiles.filter(t=>t.state==='unknown'&&neReach(s,t)&&neSettlements(s).some(a=>hexDist(a,t)>0))}
function moveColonist(s,fromId,toId){const n=s.newEarth,a=neTile(s,fromId),b=neTile(s,toId);if(!n.redeploy)return{ok:false,msg:'Neuaufstellung ist nur in der ersten New-Earth-Runde frei.'};if(!a?.settlement||!b?.settlement)return{ok:false,msg:'Nur zwischen Siedlungen.'};if((a.colonists||0)<=1)return{ok:false,msg:'Mindestens 1 Siedler muss dort bleiben.'};a.colonists--;b.colonists=(b.colonists||0)+1;return{ok:true,msg:'Siedler neu verteilt.'}}
const ALIEN_RESEARCH=[
{id:'xenobiology',path:'salvage',name:'Xenobiologie',cost:3,effect:'Biologische Funde −1 W Analyse.'},
{id:'crystalPower',path:'salvage',name:'Kristallenergie',cost:4,effect:'Mineral-Minen +1 M/Runde.'},
{id:'alienCartography',path:'salvage',name:'Alien-Kartografie',cost:4,effect:'Rover-Reichweite +1.'},
{id:'adaptiveHab',path:'salvage',name:'Adaptive Habitate',cost:5,effect:'Neue Siedlungen −1 M.'},
{id:'linguistics',path:'contact',name:'Musterlinguistik',cost:3,effect:'Signale entschlüsseln; Kontaktaktionen werden möglich.'},
{id:'resonance',path:'contact',name:'Resonanzprotokoll',cost:4,effect:'Kontakt kostet 1 W weniger.'},
{id:'exchange',path:'contact',name:'Wissensaustausch',cost:5,effect:'Nach erfolgreichem Kontakt +1 flexible Produktion/Runde.'}
];
function hasAlien(s,id){return !!s.newEarth?.alienResearch?.includes(id)}
function alienResearch(s,id){const n=s.newEarth,x=ALIEN_RESEARCH.find(x=>x.id===id);if(!x)return{ok:false,msg:'Unbekannte Forschung.'};if(hasAlien(s,id))return{ok:false,msg:'Bereits erforscht.'};if(x.path==='contact'&&!n.contactUnlocked)return{ok:false,msg:'Kontaktforschung wird durch ein analysiertes Signal freigeschaltet.'};const firstLabDiscount=neHas(s,'exobioLab')&&n.alienResearch.length===0?1:0,cost=Math.max(1,x.cost-firstLabDiscount);if(n.science<cost||n.actions<1)return{ok:false,msg:`Benötigt ${cost} W und 1 Aktion.`};n.science-=cost;n.actions--;n.alienResearch.push(id);n.alienMilestones=n.alienMilestones||0;const salvage=n.alienResearch.filter(id=>ALIEN_RESEARCH.find(x=>x.id===id)?.path==='salvage').length;if(salvage>=1&&n.alienMilestones<1){n.vp++;n.alienMilestones=1}const won=checkMissions(s);return{ok:true,msg:`${x.name} erforscht.${won.length?' Mission '+won.map(x=>x.name).join(', ')+' erfüllt!':''}`}}
function contactAliens(s){const n=s.newEarth;if(!n.contactUnlocked)return{ok:false,msg:'Noch kein entschlüsselbares Alien-Signal gefunden.'};if(!hasAlien(s,'linguistics'))return{ok:false,msg:'Erforsche zuerst Musterlinguistik.'};if(n.contactLevel>=3)return{ok:false,msg:'Stabiler Kontakt besteht bereits.'};let cost=[0,3,4,5][n.contactLevel+1]-(hasAlien(s,'resonance')?1:0);cost=Math.max(2,cost);if(n.actions<1||n.science<cost)return{ok:false,msg:`Kontaktstufe ${n.contactLevel+1}: benötigt 1 Aktion und ${cost} W.`};n.actions--;n.science-=cost;n.contactLevel++;if(n.contactLevel===1){n.vp+=1;n.contactProd=(n.contactProd||0)+1}if(n.contactLevel===2){n.vp+=1;n.contactProd=(n.contactProd||0)+1;n.radius+=1}if(n.contactLevel===3){n.vp+=2;n.contactProd=(n.contactProd||0)+1}if(hasAlien(s,'exchange'))n.contactProd=(n.contactProd||0)+1;const won=checkMissions(s);return{ok:true,msg:`Alien-Kontakt Stufe ${n.contactLevel} hergestellt: ${n.contactLevel===1?'Antwort empfangen · +1 SP, +1 flexible Produktion':n.contactLevel===2?'Austausch · +1 SP, +1 Reichweite, +1 flexible Produktion':'Verständigung · +2 SP, +1 flexible Produktion'}${won.length?' · Mission '+won.map(x=>x.name).join(', '):''}`}}
function neCost(s,type){const n=s.newEarth;let c=D.NEW_EARTH.buildings[type].cost;if(neHas(s,'fabrication')&&!['settlement','rover'].includes(type))c--;if(expert(s,'sato')&&n.first.building)c-=2;if(neHas(s,'builders')&&n.first.building&&type!=='settlement')c=0;else if(neHas(s,'builders')&&n.first.secondBuilding&&type!=='settlement')c-=2;if(type==='farm'&&n.first.farm){if(neHas(s,'extremophile'))c=0;if(neHas(s,'robotFarm'))c-=2}if(type==='mine'&&n.first.mine){if(neHas(s,'autonomousMining'))c-=3;if(expert(s,'johnson'))c-=2}if(type==='settlement'&&n.first.settlement&&neHas(s,'habitats'))c-=3;return Math.max(0,c)}
function neFoodProd(s){const n=s.newEarth;return 1+2*n.buildings.farm+(expert(s,'alvarez')?n.buildings.farm:0)+(n.bonusFoodProd||0)+(neHas(s,'foodRecycler')?2:0)+(neHas(s,'extremophile')?1:0)}
function strategyProfile(s){const n=s.newEarth||{};return{
 research:(n.buildings?.lab||0)+(expert(s,'okafor')?1:0)+(neHas(s,'exobioLab')?1:0)+(n.alienResearch?.length||0),
 industry:(n.buildings?.mine||0)+(expert(s,'sato')?1:0)+(expert(s,'johnson')?1:0)+(neHas(s,'fabrication')?1:0),
 expansion:(n.settlements||0)+(n.buildings?.farm||0)+(expert(s,'alvarez')?1:0)+(neHas(s,'habitats')?1:0),
 exploration:Math.floor((n.roverExplored||0)/2)+(expert(s,'johnson')?1:0)+(expert(s,'mei')?1:0)+(neHas(s,'drones')?1:0)+(neHas(s,'longRover')?1:0)
}}
function convertResource(s,kind){const n=s.newEarth;if(n.actions<1)return{ok:false,msg:'Keine Aktion.'};if(kind==='scienceBuild'){if(n.science<3)return{ok:false,msg:'Benötigt 3 W.'};n.science-=3;n.material+=3;n.actions--;return{ok:true,msg:'Forschungsfabrikation: 3 W → 2 M.'}}if(kind==='foodBuild'){if(n.food<4)return{ok:false,msg:'Benötigt 4 Nahrung.'};n.food-=4;n.material+=2;n.actions--;return{ok:true,msg:'Biowerkstoffe: 4 Nahrung → 2 M.'}}if(kind==='industryResearch'){if(n.material<3)return{ok:false,msg:'Benötigt 3 M.'};n.material-=3;n.science+=3;n.actions--;return{ok:true,msg:'Industrieforschung: 3 M → 2 W.'}}return{ok:false,msg:'Unbekannte Umwandlung.'}}
function neBuild(s,type,tileId){const n=s.newEarth,t=neTile(s,tileId||n.selectedTile);if(n.actions<1)return{ok:false,msg:'Keine Aktion.'};if(!t||t.state==='unknown')return{ok:false,msg:'Wähle zuerst ein entdecktes Feld.'};if(t.blockedBy)return{ok:false,msg:`Dieses Gebiet wurde bereits von ${t.blockedBy} beansprucht.`};let c=neCost(s,type);if(type==='settlement'&&t.discovery?.id==='canyon'&&t.analyzed)c=Math.max(0,c-1);if(type==='settlement'&&hasAlien(s,'adaptiveHab'))c=Math.max(0,c-1);if(n.material<c)return{ok:false,msg:`Benötigt ${c} M.`};if(type==='settlement'){if(t.settlement)return{ok:false,msg:'Hier steht bereits eine Siedlung.'};if(!t.analyzed&&t.discovery?.id!=='plain')return{ok:false,msg:'Sonderfund zuerst analysieren.'};const supplyNeed=neHas(s,'foodRecycler')?0:n.settlements+1;if(neFoodProd(s)<supplyNeed)return{ok:false,msg:'Versorgung fehlt.'}}else if(type!=='rover'&&!neSettlements(s).some(a=>hexDist(a,t)<=1))return{ok:false,msg:'Gebäude müssen neben einer Siedlung liegen.'};if(type==='mine'&&t.discovery?.terrain&&!['mineral','canyon','plain'].includes(t.discovery.terrain))return{ok:false,msg:'Dieses Gelände eignet sich nicht für eine Mine.'};if(type==='farm'&&t.discovery?.terrain&&!['fertile','ice','plain'].includes(t.discovery.terrain))return{ok:false,msg:'Dieses Gelände eignet sich nicht für eine Farm.'};n.actions--;n.material-=c;if(type==='settlement'){n.settlements++;t.settlement=true;t.state='settled';n.first.settlement=false;const milestone=Math.floor((n.settlements-1)/2);if(milestone>(n.settlementMilestones||0)){n.vp++;n.settlementMilestones=milestone}}else{n.buildings[type]++;t.buildings.push(type);const productive=(type==='mine'&&['mineral','canyon'].includes(t.discovery?.terrain))||(type==='farm'&&['fertile','ice'].includes(t.discovery?.terrain))||(type==='lab'&&t.discovery?.terrain==='ruin');if(productive&&t.analyzed&&!n.developed.includes(t.id)){n.developed.push(t.id);n.vp++}}if(type==='farm')n.first.farm=false;if(type==='mine'){n.first.mine=false;n.industryMilestones=n.industryMilestones||0;const im=n.buildings.mine>=2?1:0;if(im>n.industryMilestones){n.vp+=im-n.industryMilestones;n.industryMilestones=im}}if(type!=='settlement'){if(n.first.building)n.first.building=false;else n.first.secondBuilding=false}const won=checkMissions(s);return{ok:true,msg:`${D.NEW_EARTH.buildings[type].name} gebaut. −${c} M${type==='settlement'?(Math.floor((n.settlements-1)/2)===(n.settlementMilestones||0)&&n.settlements%2===1?' · Siedlungsnetz +1 SP':''):(n.developed?.includes(t.id)&&t.analyzed&&t.discovery?.id!=='plain'?' · erschlossener Fund +1 SP':'')}${won.length?' · Mission: '+won.map(x=>x.name).join(', ')+' +'+won.reduce((a,x)=>a+x.vp,0)+' SP':''}`}}
function explorationOptions(s,forced){const n=s.newEarth;let count=3+(neHas(s,'drones')?1:0)+(expert(s,'johnson')?1:0)+(expert(s,'okafor')?1:0)+(expert(s,'mei')?1:0);let pool=D.DISCOVERIES.slice();if(forced){const d=D.DISCOVERIES.find(x=>x.id===forced);if(d&&!pool.some(x=>x.id===d.id))pool.unshift(d)}let out=[];while(pool.length&&out.length<count){const i=Math.floor(rand(s)*pool.length);out.push(pool.splice(i,1)[0])}return out}
function explore(s,id,forced,tileId){const n=s.newEarth,t=neTile(s,tileId||n.selectedTile);if(n.actions<1)return{ok:false,msg:'Keine Aktion.'};if(n.buildings.rover<1)return{ok:false,msg:'Baue zuerst einen Rover.'};if(!t||t.state!=='unknown'||!neReach(s,t))return{ok:false,msg:'Dieses Feld ist nicht erreichbar.'};const o=explorationOptions(s,forced),d=o.find(x=>x.id===id)||o[0];if(!d)return{ok:false,msg:'Nichts mehr zu entdecken.'};n.actions--;n.roverExplored=(n.roverExplored||0)+1;const oldMil=n.exploreMilestones||0,newMil=n.roverExplored>=7?2:n.roverExplored>=3?1:0;if(newMil>oldMil){n.vp+=newMil-oldMil;n.exploreMilestones=newMil}t.state='discovered';t.discovery=clone(d);t.analyzed=false;n.known.push(clone(d));n.selectedTile=t.id;return{ok:true,options:o,choice:d,tile:t}}
function analyze(s,id,tileId){const n=s.newEarth,t=neTile(s,tileId||n.selectedTile),d=t?.discovery;if(!t||!d||t.state==='unknown')return{ok:false,msg:'Fund nicht bekannt.'};if(t.blockedBy)return{ok:false,msg:`Der Fund wurde bereits von ${t.blockedBy} beansprucht.`};if(t.analyzed)return{ok:false,msg:'Bereits analysiert.'};let c=d.analysis||0;if(n.rounds===0&&t.state==='surveyed')c=Math.max(0,c-1);if(['alien','biology'].includes(d.type)&&neHas(s,'exobioLab'))c-=2;if(d.type==='biology'&&hasAlien(s,'xenobiology'))c--;if(['alien','biology'].includes(d.type)&&expert(s,'okafor'))c--;c=Math.max(0,c);if(n.actions<1||n.science<c)return{ok:false,msg:`Benötigt Aktion und ${c} W.`};n.actions--;n.science-=c;n.vp+=d.vp||0;if(['ruin','signal'].includes(d.id)){n.relics=(n.relics||0)+1;if(n.relics===1||n.relics===3)n.vp++}if(d.id==='signal')n.contactUnlocked=true;if(neHas(s,'exobioLab')&&n.first.exobio&&['alien','biology'].includes(d.type)){n.vp++;n.first.exobio=false}n.material+=d.material||0;n.science+=d.science||0;if(d.id==='ice')n.food+=2;if(d.id==='microbes')n.bonusFoodProd=(n.bonusFoodProd||0)+1;t.analyzed=true;t.state=t.settlement?'settled':'analyzed';n.known=n.known.filter(x=>x.id!==d.id);n.analyzed.push(`${t.id}:${d.id}`);const won=checkMissions(s);return{ok:true,msg:`${d.name} analysiert: −${c} W${d.vp?` · +${d.vp} SP`:''}. ${d.reward||d.bonus||''}${won.length?' · Mission erfüllt: '+won.map(x=>x.name).join(', '):''}`}}
function neProduction(s){const n=s.newEarth;let mineBonus=0,farmBonus=0;for(const t of n.tiles||[]){if(t.analyzed&&t.discovery?.id==='mineral'&&t.buildings.includes('mine'))mineBonus+=(hasAlien(s,'crystalPower')?2:1)+(expert(s,'johnson')?1:0);if(t.analyzed&&t.discovery?.id==='fertile'&&t.buildings.includes('farm'))farmBonus++}let networkMaterial=0,networkFood=0,networkScience=0;
for(const t of n.tiles||[]){if(!t.buildings?.length)continue;const nearSettlement=neSettlements(s).some(a=>hexDist(a,t)===1);if(!nearSettlement)continue;if(t.buildings.includes('mine')&&t.discovery?.terrain==='canyon')networkMaterial++;if(t.buildings.includes('farm')&&t.discovery?.id==='ice')networkFood++;if(t.buildings.includes('lab')&&t.discovery?.terrain==='ruin'&&t.analyzed)networkScience++}
const prof=strategyProfile(s);if(n.contactProd)n.flexProd=(n.flexProd||0)+0;const techMaterial=(neHas(s,'fabrication')?1:0),techFood=(neHas(s,'extremophile')?1:0),techScience=(neHas(s,'exobioLab')?2:0);let flexM=0,flexF=0,flexS=0;const totalFlex=(n.flexProd||0)+(n.contactProd||0);if(totalFlex){const vals=[['material',n.material],['food',n.food],['science',n.science]].sort((a,b)=>a[1]-b[1]);if(vals[0][0]==='material')flexM+=totalFlex;else if(vals[0][0]==='food')flexF+=totalFlex;else flexS+=totalFlex}const p={material:1+techMaterial+2*n.buildings.mine+mineBonus+networkMaterial+(n.bonusMaterialProd||0)+(n.prefabProd?.material||0)+flexM+(prof.industry>=5?2:0),food:1+techFood+2*n.buildings.farm+farmBonus+networkFood+(n.prefabProd?.food||0)+(expert(s,'alvarez')?n.buildings.farm:0)+(n.bonusFoodProd||0)+(neHas(s,'foodRecycler')?2:0)+flexF+(prof.expansion>=6?1:0),science:techScience+2*n.buildings.lab+networkScience+(n.prefabProd?.science||0)+(expert(s,'okafor')?n.buildings.lab:0)+(n.bonusScienceProd||0)+flexS+(prof.research>=3?1:0)+(prof.research>=5?2:0)};n.material+=p.material;n.food+=p.food;n.science+=p.science;return p}
const MISSIONS=[
{id:'selfSufficient',name:'Autarke Kolonie',vp:2,desc:'2 Siedlungen, mindestens 2 Farmen und Nahrungsproduktion ≥ Bevölkerung +2.',test:s=>s.newEarth.settlements>=2&&s.newEarth.buildings.farm>=2&&neFoodProd(s)>=s.newEarth.population+2},
{id:'xenoScience',name:'Fremde Wissenschaft',vp:2,desc:'3 Sonderfunde analysiert, darunter mindestens 1 Alienfund.',test:s=>{const a=s.newEarth.tiles.filter(t=>t.analyzed&&t.discovery?.id!=='plain');return a.length>=3&&a.some(t=>t.discovery?.type==='alien')}},
{id:'industryHub',name:'Industriezentrum',vp:2,desc:'Mindestens 2 Minen und Materialproduktion ≥ 7.',test:s=>{if(s.newEarth.buildings.mine<2)return false;const c=clone(s),p=neProduction(c);return p.material>=7}},
{id:'frontier',name:'Neue Grenze',vp:2,desc:'2 Siedlungen und mindestens 5 mit dem Rover neu erkundete Felder.',test:s=>s.newEarth.settlements>=2&&(s.newEarth.roverExplored||0)>=5},
{id:'alienTech',name:'Neue Wissenschaft',vp:2,desc:'2 geborgene Alien-Technologien und mindestens 1 Labor.',test:s=>s.newEarth.alienResearch.filter(id=>ALIEN_RESEARCH.find(x=>x.id===id)?.path==='salvage').length>=2&&s.newEarth.buildings.lab>=1},
{id:'firstContact',name:'Erster Kontakt',vp:2,desc:'Kontaktstufe 2 erreichen und mindestens 1 Labor betreiben.',test:s=>(s.newEarth.contactLevel||0)>=2&&s.newEarth.buildings.lab>=1}
];
function initMissions(s){const pool=MISSIONS.slice(),out=[];while(out.length<4&&pool.length){const i=Math.floor(rand(s)*pool.length);out.push({...pool.splice(i,1)[0],selected:false,claimed:false})}s.newEarth.missions=out}
function selectMission(s,id){const n=s.newEarth,m=(n.missions||[]).find(x=>x.id===id);if(!m)return{ok:false,msg:'Ziel nicht verfügbar.'};if(m.selected)return{ok:false,msg:'Ziel bereits gewählt.'};if(n.missions.filter(x=>x.selected).length>=2)return{ok:false,msg:'Du hast bereits 2 Kolonieziele gewählt.'};m.selected=true;const won=checkMissions(s);return{ok:true,msg:`Kolonieziel gewählt: ${m.name}.${won.length?' Direkt erfüllt!':''}`}}
function checkMissions(s){const won=[];for(const m of s.newEarth.missions||[])if(m.selected&&!m.claimed&&MISSIONS.find(x=>x.id===m.id).test(s)){m.claimed=true;s.newEarth.vp+=m.vp;won.push(m)}return won}
function endRound(s){if(s.phase==='earth'){if(!s.event)drawEvent(s);const i=income(s);s.money+=i.money;s.material+=i.material;s.science+=i.science;s.inactiveMeeples=0;s.round++;s.actions=s.population;s.event=null;s.highTechUsed=false;makeForecast(s);s._built=false;s.pendingRocketPenalty=false;return i}const p=neProduction(s);s.newEarth.rounds++;s.newEarth.prodHistory.push(clone(p));if(s.newEarth.vp>=D.BALANCE.winVP)s.gameOver=true;s.round++;s.newEarth.actions=s.newEarth.population;return p}
const api={newGame,danger,income,peekEvent,drawEvent,moveMeeple,vargaSkip,buildEarth,buyProject,hireExpert,researchTech,buildTech,rocketCost,buildRocket,capacities,transportableTechs,launch,neCost,neBuild,neFoodProd,explorationOptions,explore,analyze,neProduction,frontierTiles,neTile,neReach,hexDist,moveColonist,ALIEN_RESEARCH,alienResearch,contactAliens,hasAlien,strategyProfile,convertResource,MISSIONS,selectMission,checkMissions,refreshProjectMarket,refillProjectMarket,refillExpertMarket,makeForecast,forecastRegions,endRound,costText,exportState:JSON.stringify,importState:JSON.parse,has,expert};root.NewEarthEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
