(function(root){
const D=root.NewEarthData||(typeof require!=='undefined'?require('./data.js'):null),E=root.NewEarthEngine||(typeof require!=='undefined'?require('./engine.js'):null);
const afford=(s,c)=>(!c.money||s.money>=c.money)&&(!c.material||s.material>=c.material)&&(!c.science||s.science>=c.science);
function tryEarth(s,launchRound,u){const r=s.round,c=E.capacities(s);if(r>=launchRound-2){if(c.people<5&&afford(s,E.rocketCost(s,'habitat'))){if(E.buildRocket(s,'habitat').ok)return}if(c.resources<9&&afford(s,E.rocketCost(s,'cargo'))){if(E.buildRocket(s,'cargo').ok)return}if(c.tech<E.transportableTechs(s).length+1&&afford(s,E.rocketCost(s,'tech'))){if(E.buildRocket(s,'tech').ok)return}}
const pr=['drones','extremophile','fabrication','exobioLab','habitats','longRover','foodRecycler','builders','oxygen','fusion'];for(const id of pr){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(s.technologies[id]==='researched'&&afford(s,t.cost)){if(E.buildTech(s,id).ok){u.tech[id]=(u.tech[id]||0)+1;return}}}for(const id of pr){const t=D.TECHNOLOGIES.find(x=>x.id===id);if(s.technologies[id]==='locked'&&s.science>=Math.max(0,t.research-1)){if(E.researchTech(s,id).ok)return}}
if(r<=launchRound-2){for(const id of ['johnson','okafor','sato','williams','alvarez','mei','petrov','varga']){const x=D.EXPERTS.find(e=>e.id===id);if(!s.experts.includes(id)&&afford(s,x.cost)){if(E.hireExpert(s,id).ok){u.expert[id]=(u.expert[id]||0)+1;return}}}for(const id of ['openScience','resourceDepot','recycling','mobileResearch','robotFarm','autonomousMining','globalContracts']){const p=D.PROJECTS.find(x=>x.id===id);if(!s.projects.includes(id)&&afford(s,p.cost)){if(E.buyProject(s,id).ok){u.project[id]=(u.project[id]||0)+1;return}}}}
for(const [bid,type] of [['researchCenter','research'],['mine','resources'],['factory','industry']]){const b=D.STANDARD_BUILDINGS[bid],reg=s.regions.find(x=>x.type===type&&x.status&&x.buildings.length===0);if(reg&&afford(s,b.cost)){if(E.buildEarth(s,bid,reg.id).ok)return}}s.actions=0}
function load(s){const c=E.capacities(s),experts=s.experts.slice(0,Math.max(0,c.people-Math.min(s.population,c.people))),population=Math.min(s.population,Math.max(1,c.people-experts.length));return{population,experts,material:Math.min(s.material,c.resources),tech:E.transportableTechs(s).slice(0,c.tech)}}
function tryNE(s){const n=s.newEarth;for(const d of n.known.slice().sort((a,b)=>a.analysis-b.analysis))if(E.analyze(s,d.id).ok)return;if(n.buildings.lab<2&&n.material>=E.neCost(s,'lab'))if(E.neBuild(s,'lab').ok)return;if(n.buildings.rover<1&&n.material>=E.neCost(s,'rover'))if(E.neBuild(s,'rover').ok)return;if(n.buildings.mine<2&&n.material>=E.neCost(s,'mine'))if(E.neBuild(s,'mine').ok)return;if(n.buildings.farm<2&&n.material>=E.neCost(s,'farm'))if(E.neBuild(s,'farm').ok)return;if(n.buildings.rover&&n.known.length<4){const o=E.explorationOptions(s);if(o.length&&E.explore(s,o[0].id).ok)return}if(n.material>=E.neCost(s,'settlement')&&E.neFoodProd(s)>=(E.has(s,'foodRecycler')?0:n.settlements+1))if(E.neBuild(s,'settlement').ok)return;if(n.material>=E.neCost(s,'lab'))if(E.neBuild(s,'lab').ok)return;if(n.material>=E.neCost(s,'mine'))if(E.neBuild(s,'mine').ok)return;n.actions=0}
function runOne(launchRound,seed=1,det=false){const s=E.newGame(seed),usage={tech:{},expert:{},project:{}},vpTimeline={};let landingRound=null;while(!s.gameOver&&s.round<40){if(s.phase==='earth'){if(!s.event)E.drawEvent(s,det?({1:'heat',2:'brainDrain',3:'supply',4:'drought',5:'energy',6:'infra',7:'cascade'}[s.round]):undefined);while(s.actions>0&&s.round<launchRound)tryEarth(s,launchRound,usage);if(s.round>=launchRound){if(E.launch(s,load(s)).ok){landingRound=s.round;continue}}E.endRound(s)}else{while(s.newEarth.actions>0&&!s.gameOver)tryNE(s);E.endRound(s);vpTimeline[s.round]=s.newEarth.vp}}
const n=s.newEarth||{prodHistory:[],vp:0,tech:[],experts:[],population:0,landingMaterial:0},cap=E.capacities(s);return{launchRound,finishRound:s.gameOver?s.round:null,landingRound,vpTimeline,prod1:n.prodHistory[0]||null,prod2:n.prodHistory[1]||null,prod3:n.prodHistory[2]||null,earthLosses:s.earthLosses,techValue:n.tech.length,unused:{people:Math.max(0,cap.people-n.population-n.experts.length),resources:Math.max(0,cap.resources-(n.landingMaterial||0)),tech:Math.max(0,cap.tech-n.tech.length)},usage,finalVP:n.vp}}
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;function aggregate(rows){const sum=kind=>{const o={};for(const r of rows)for(const[k,v]of Object.entries(r.usage[kind]))o[k]=(o[k]||0)+v;return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,v/rows.length]))},prod=i=>({material:avg(rows.map(r=>r[`prod${i}`]?.material||0)),food:avg(rows.map(r=>r[`prod${i}`]?.food||0)),science:avg(rows.map(r=>r[`prod${i}`]?.science||0))});return{launchRound:rows[0].launchRound,n:rows.length,finishRound:avg(rows.map(r=>r.finishRound).filter(Boolean)),winRate:rows.filter(r=>r.finishRound).length/rows.length,prod1:prod(1),prod2:prod(2),prod3:prod(3),earthRegions:avg(rows.map(r=>r.earthLosses.regions)),earthBuildings:avg(rows.map(r=>r.earthLosses.buildings)),earthMeeples:avg(rows.map(r=>r.earthLosses.meeples)),techValue:avg(rows.map(r=>r.techValue)),unusedPeople:avg(rows.map(r=>r.unused.people)),unusedResources:avg(rows.map(r=>r.unused.resources)),unusedTech:avg(rows.map(r=>r.unused.tech)),usage:{tech:sum('tech'),expert:sum('expert'),project:sum('project')}}}
function compareDeterministic(){const rows=[3,4,5,6,7].map(r=>runOne(r,424242,true));for(const later of rows){later.earlyLead={};for(const early of rows.filter(x=>x.launchRound<later.launchRound))later.earlyLead[early.launchRound]=early.vpTimeline[later.launchRound]||0}return rows}function monteCarlo(n=10000){return[3,4,5,6,7].map(r=>aggregate(Array.from({length:n},(_,i)=>runOne(r,100000*r+i))))}
const api={runOne,aggregate,compareDeterministic,monteCarlo};root.NewEarthSimulation=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
